# Generated by Django 2.2.10 on 2020-06-28 20:57

from django.db import migrations
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
  # Creating default admin user
  User.objects.create_user(
    username='admin',
    password='admin',
    is_staff=True
  )


class Migration(migrations.Migration):
  dependencies = [
    ('polls', '0001_initial'),
  ]

  operations = [
    migrations.RunPython(forwards_func)
  ]
